{
    "vulnerability_insights": {
        "metadata": {
            "timestamp": "2025-08-14T10:07:32.332136+05:30",
            "package": "numpy",
            "version": "latest",
            "ecosystem": "PyPI"
        },
        "developer_view": [
            {
                "vulnerability_id": "GHSA-2fc2-6r4j-p65h",
                "summary": "Numpy arbitrary file write via symlink attack",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                    "level": "Medium"
                },
                "fixed_versions": [
                    "1.8.1"
                ],
                "impact": "(1) core/tests/test_memmap",
                "remediation_steps": "Upgrade to 1.8.1",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1859"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/pull/4262"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                    },
                    {
                        "type": "advisory",
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-2fc2-6r4j-p65h"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2018-34.yaml"
                    },
                    {
                        "type": "advisory",
                        "url": "https://web.archive.org/web/20200228165750/http://www.securityfocus.com/bid/65440"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-5545-2q6w-2gh6",
                "summary": "NumPy NULL Pointer Dereference",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "level": "High"
                },
                "fixed_versions": [
                    "1.19"
                ],
                "impact": "Null Pointer Dereference vulnerability exists in numpy",
                "remediation_steps": "Upgrade to 1.19",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41495"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/19038"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml"
                    },
                    {
                        "type": "advisory",
                        "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-9fq2-x9r6-wfmf",
                "summary": "Numpy Deserialization of Untrusted Data",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                    "level": "Critical"
                },
                "fixed_versions": [],
                "impact": "** DISPUTED **   An issue was discovered in NumPy 1",
                "remediation_steps": "No fix available",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/12759"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/pull/12889"
                    },
                    {
                        "type": "advisory",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                    },
                    {
                        "type": "advisory",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2019-108.yaml"
                    },
                    {
                        "type": "advisory",
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                    },
                    {
                        "type": "advisory",
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                    },
                    {
                        "type": "advisory",
                        "url": "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-cw6w-4rcx-xphc",
                "summary": "Arbitrary file write in NumPy",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                    "level": "Medium"
                },
                "fixed_versions": [
                    "1.8.1"
                ],
                "impact": "__init__",
                "remediation_steps": "Upgrade to 1.8.1",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1858"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/pull/4262"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                    },
                    {
                        "type": "advisory",
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-cw6w-4rcx-xphc"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2018-33.yaml"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.securityfocus.com/bid/65441"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-f7c7-j99h-c22f",
                "summary": "Buffer Copy without Checking Size of Input in NumPy",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "level": "Medium"
                },
                "fixed_versions": [
                    "1.19"
                ],
                "impact": "Buffer overflow in the array_from_pyobj function of fortranobject",
                "remediation_steps": "Upgrade to 1.19",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41496"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/19000"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-fpfv-jqm9-f5jm",
                "summary": "Incorrect Comparison in NumPy",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                    "level": "Medium"
                },
                "fixed_versions": [
                    "1.22"
                ],
                "impact": "Incomplete string comparison in the numpy",
                "remediation_steps": "Upgrade to 1.22",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/18993"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                    },
                    {
                        "type": "advisory",
                        "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                    }
                ]
            },
            {
                "vulnerability_id": "GHSA-frgw-fgh6-9g52",
                "summary": "Numpy missing input validation",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "CVSS_V3",
                    "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "level": "High"
                },
                "fixed_versions": [
                    "1.13.3"
                ],
                "impact": "The numpy",
                "remediation_steps": "Upgrade to 1.13.3",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12852"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/releases/tag/v1.13.3"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2017-1.yaml"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2017-1",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "1.13.3"
                ],
                "impact": "The numpy",
                "remediation_steps": "Upgrade to 1.13.3",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2018-33",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                ],
                "impact": "__init__",
                "remediation_steps": "Upgrade to 0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/pull/4262"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                    },
                    {
                        "type": "advisory",
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.securityfocus.com/bid/65441"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-cw6w-4rcx-xphc"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2018-34",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                ],
                "impact": "(1) core/tests/test_memmap",
                "remediation_steps": "Upgrade to 0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/pull/4262"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                    },
                    {
                        "type": "advisory",
                        "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.securityfocus.com/bid/65440"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-2fc2-6r4j-p65h"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2019-108",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "1.16.1"
                ],
                "impact": "** DISPUTED **   An issue was discovered in NumPy 1",
                "remediation_steps": "Upgrade to 1.16.1",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/12759"
                    },
                    {
                        "type": "advisory",
                        "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                    },
                    {
                        "type": "advisory",
                        "url": "http://www.securityfocus.com/bid/106670"
                    },
                    {
                        "type": "advisory",
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                    },
                    {
                        "type": "advisory",
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                    },
                    {
                        "type": "advisory",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                    },
                    {
                        "type": "advisory",
                        "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2021-856",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "1.19.1"
                ],
                "impact": "Null Pointer Dereference vulnerability exists in numpy",
                "remediation_steps": "Upgrade to 1.19.1",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/19038"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                    }
                ]
            },
            {
                "vulnerability_id": "PYSEC-2021-857",
                "summary": "",
                "affected_components": [
                    "numpy"
                ],
                "severity": {
                    "type": "Unknown",
                    "score": null,
                    "level": "Unknown"
                },
                "fixed_versions": [
                    "1.19.0"
                ],
                "impact": "Buffer overflow in the array_from_pyobj function of fortranobject",
                "remediation_steps": "Upgrade to 1.19.0",
                "references": [
                    {
                        "type": "advisory",
                        "url": "https://github.com/numpy/numpy/issues/19000"
                    },
                    {
                        "type": "advisory",
                        "url": "https://github.com/advisories/GHSA-f7c7-j99h-c22f"
                    }
                ]
            }
        ],
        "tech_leader_view": {
            "total_vulnerabilities": 13,
            "severity_breakdown": {
                "critical": 1,
                "high": 2,
                "medium": 4,
                "low": 0
            }
        }
    }
}